# Generated by Django 5.1.7 on 2025-05-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersinfo',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
