# Generated by Django 6.1.1 on 2026-09-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('luxury', '0018_spascanneditem_done_at_spascanneditem_done_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPointLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('points', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_logs', to='customers.customerprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='POSReferralRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('referral_code', models.CharField(max_length=30)),
                ('note', models.CharField(default='Referral', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('referred_by_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_referral_records', to='customers.customerprofile')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='luxury.worker')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.IntegerField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claimed_transactions', to='customers.customerprofile')),
            ],
            options={
                'unique_together': {('transaction_id', 'transaction_type')},
            },
        ),
    ]
