# Generated by Django 5.1.7 on 2025-04-18 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luxury", "0002_transaction_scanneditem_worker_transaction_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scanneditem",
            name="item_name",
        ),
        migrations.RemoveField(
            model_name="scanneditem",
            name="total_per_item",
        ),
        migrations.RemoveField(
            model_name="scanneditem",
            name="unit_price",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="amount_paid",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="balance_due",
        ),
        migrations.AddField(
            model_name="scanneditem",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="luxury.product",
            ),
        ),
    ]
