# Generated by Django 5.1.7 on 2025-04-18 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luxury", "0003_remove_scanneditem_item_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scanneditem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="luxury.product"
            ),
        ),
    ]
