# Generated by Django 5.1.7 on 2025-04-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luxury", "0004_alter_scanneditem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
