# Generated by Django 5.1.7 on 2025-04-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luxury", "0007_scanneditem_price_at_sale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
