# Generated by Django 5.1.7 on 2025-04-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("luxury", "0008_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="temp/"),
        ),
    ]
