# Generated by Django 5.1.7 on 2025-05-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxury', '0010_booking_service_bookedservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
