# Generated by Django 5.1.7 on 2025-05-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxury', '0012_service_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedservice',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
