# Generated by Django 5.1.7 on 2025-05-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxury', '0013_bookedservice_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedservice',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
