# Generated by Django 5.1.7 on 2025-05-31 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxury', '0014_alter_bookedservice_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SPATransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxury.worker')),
            ],
        ),
        migrations.CreateModel(
            name='SPAScannedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_sale', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luxury.product')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luxury.service')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_items', to='luxury.spatransaction')),
            ],
        ),
    ]
