# Generated by Django 5.1.7 on 2025-05-31 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxury', '0015_spatransaction_spascanneditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luxury.luxurybranch')),
            ],
        ),
        migrations.AlterField(
            model_name='spascanneditem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='luxury.spaproduct'),
        ),
    ]
