# Generated by Django 5.1.7 on 2025-06-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxury', '0016_spaproduct_alter_spascanneditem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='spascanneditem',
            name='status',
            field=models.CharField(default='Pending'),
        ),
    ]
