# Generated by Django 5.1.7 on 2025-06-07 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luxury', '0017_spascanneditem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='spascanneditem',
            name='done_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spascanneditem',
            name='done_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_items', to='luxury.worker'),
        ),
    ]
