# Generated by Django 5.1.7 on 2025-04-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authenticate", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Worker",
        ),
    ]
